[package]
name = "wasmer-examples/astro-wasmer-starter"
version = "0.2.1"
description = "Wasmer Astro.dev starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/astro-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
